<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit575880b472301c37e1646760447e4bbe
{
    public static $prefixLengthsPsr4 = array (
        'A' => 
        array (
            'App\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'App\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'AltoRouter' => __DIR__ . '/..' . '/altorouter/altorouter/AltoRouter.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit575880b472301c37e1646760447e4bbe::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit575880b472301c37e1646760447e4bbe::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit575880b472301c37e1646760447e4bbe::$classMap;

        }, null, ClassLoader::class);
    }
}
